name = "MyApp"
uuid = "f943f3d7-887a-4ed5-b0c0-a1d6899aa8f5"
authors = ["Kristoffer Carlsson <kristoffer.carlsson@juliacomputing.com>"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
HelloWorldC_jll = "dca1746e-5efc-54fc-8249-22745bc95a49"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
